### ISSUE TITLE
SIA Init Container Shut Downs Successfully when Athenz Domain is not found and fails to read instance certificate

### ISSUE THREAD

**Issue by mlajkim** [AthenZ/k8s-athenz-sia#55]
# Background
As the backup feature is introduced, the flow of the SIA has been modified and it fails to repeat its `IdentityProvisioning` when identity has not been successfully prepared as the following diagram with red square. (This did not happen is SIA v2.1.0) This bug let the init container shut down when instance certificate is not yet prepared.
![image](https://github.com/AthenZ/k8s-athenz-sia/assets/53258958/89dc9fe0-2463-45e3-ba4d-3e37effca910)

~Also found out it would be better to have the new `BACKUP_MODE` (the green square below) that reads instance certificate that is 3rd party generated.~
Decided not to have the backup mode, as BACKUP_MODE is only for k8s, not for others.

Also requires to implement reading instance certificate from local file, with the new implementation as following:
![image](https://github.com/AthenZ/k8s-athenz-sia/assets/53258958/d9c7aa56-1852-43bb-9ab5-427b3f153b2a)

**The following diagram is the `identitydProvisioning()` flow for your information.**
![image](https://github.com/AthenZ/k8s-athenz-sia/assets/53258958/e65dea3c-66ff-4f27-bb8f-7eb71d656241)

## TODOs
- [x] Fix the flow
- [x] Double check logs as the logs might have to be fixed
- [X] ~Introduce `file`~
- [X] Modify `athenz.env`
- [X] Apply latest: https://github.com/AthenZ/k8s-athenz-sia/pull/53
- [X] Apply Hotfix and release v3.1.2
- [X] ~(Optional) Upgrade Metrics without vulnerabilities~

**Comment by mlajkim** [comment]
Closed as all TODOs handled.
