### ISSUE TITLE
INFO, WARN, ERROR Logging Standard

### ISSUE THREAD

**Issue by mlajkim** [AthenZ/k8s-athenz-sia#63]
# Background
Currently, there is no standard or meaning differences in log level like `Error`, `Warn`, `Info` or `Debug`.
https://github.com/AthenZ/k8s-athenz-sia/pull/62#discussion_r1393977998

## TODOs
- [ ] Get the logging convention
- [ ] Write the documentation or linter for the convention
- [ ] Enforce the rules if possible
- [ ] Fix the logging type according to the rule you create
